### PR TITLE
Fsm new states

### PR DESCRIPTION
**Pull request by jlrandulfe**
Set the UTM data to the proper format. The data is uploaded correctly

Check the status of the docking station before taking off

### CODE REVIEW

**Review by F1nsk — COMMENTED** [review]
(y)

**Review by Crowdedlight — DISMISSED** [review]
Simulated with me as observer. Looks good.

**Comment by Crowdedlight** [comment]
@jlrandulfe @andkgl Had a look though the changes. Haven't simulated it, but changes looks fine. Have you simulated it, so we are able to merge?

**Comment by jlrandulfe** [comment]
We did a lot of simulations (Around 15 go and back trips) and most of the time worked (Maybe 13 completely successful and 2 partially successful).

We are still not completely sure if it reacts properly when the pathplanner sends an emergency stop for not getting into a conflictive area.

A lot of simulations had to be restarted because of an IMU error in the Gazebo core, but doesn't seem to be a error that will happen in the real drone.

There is a minor push at the end from @andkgl that was not tested.

**Comment by Crowdedlight** [comment]
Alright. so what is the plan going forward with this pull request? Quick simulation tomorrow morning, then merge and go test live? Or test live from branch then merge after?

Can we simulate emergency stop ?

**Comment by jlrandulfe** [comment]
That last point is tricky, and we couldn't figure out how to simulate it properly. It happened only once in 15 tries, and it somewhat worked. We need more practical examples for tuning it though.

I'd say to do a simulation with the current branch in 2 laptopts before leaving, merge and run in the airfield.

**Review by F1nsk — APPROVED** [review]

**Review by Crowdedlight — APPROVED** [review]

**Pull request merged**
